# Generated by Django 5.0.2 on 2024-03-02 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flower', '0001_initial'),
        ('neighbourhood', '0002_delete_userdata'),
        ('user', '0004_userdata_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighbourhoodData',
            fields=[
                ('greenScore', models.IntegerField(default=0)),
                ('name', models.CharField(default='')),
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlowerInNeighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_to_neighbourhood_fk', models.ForeignKey(max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='flower.flowerdata')),
                ('neighbourhood_to_flower_fk', models.ForeignKey(max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.neighbourhooddata')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_to_neighbourhood_fk', models.ForeignKey(max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='user.userdata')),
                ('neighbourhood_to_member_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.neighbourhooddata')),
            ],
        ),
    ]
