# Generated by Django 5.0.2 on 2024-03-03 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhooddata',
            old_name='name',
            new_name='neighbourhood_name',
        ),
    ]
