# Generated by Django 5.0.2 on 2024-03-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_rename_greenscore_neighbourhooddata_ndvi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhooddata',
            name='geoJSON',
            field=models.JSONField(verbose_name='geoJSON'),
        ),
    ]
