# Generated by Django 5.0.2 on 2024-03-03 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0008_neighbourhooddata_geojson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhooddata',
            name='geoJSON',
        ),
    ]
