# Generated by Django 5.0.2 on 2024-03-03 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('neighbourhood', '0010_neighbourhooddata_geojson'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsInNeighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_to_neightbourhood_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventdata')),
                ('neighbourhood_to_event_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.neighbourhooddata')),
            ],
        ),
    ]
