# Generated by Django 5.0.2 on 2024-03-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=10000)),
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
