# Generated by Django 5.0.2 on 2024-03-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='l_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='password',
            field=models.CharField(default='****', max_length=100),
        ),
    ]
