# Generated by Django 5.0.2 on 2024-03-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_name_userdata_f_name_userdata_l_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.CharField(default='', max_length=10000, unique=True),
        ),
    ]
