# Generated by Django 5.0.2 on 2024-03-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
