# Generated by Django 5.0.2 on 2024-03-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerData',
            fields=[
                ('name', models.CharField(default='', max_length=100)),
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
