# Generated by Django 5.0.2 on 2024-03-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_flowerdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowerdata',
            name='location',
            field=models.CharField(default=''),
        ),
    ]
