# Generated by Django 5.0.2 on 2024-03-03 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='event_location',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='pics',
            field=models.ImageField(default='', upload_to='events'),
            preserve_default=False,
        ),
    ]
